inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  Exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'spec/**/*'
  - 'db/schema.rb'
  - 'db/**/*'
  - 'config/**/*'
  - 'Guardfile'
  - 'bin/**/*'
  - 'lib/price-simulator/**/*'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  # lib/tasks/capture_plan_webpage.rake が41行ある
  # lib/tasks/target_plans.rake が 48行 ある
  # lib/tasks/deploy.rake が 52行 ある
  Max: 52

Metrics/ClassLength:
  # app/models/area_plan.rb が435行ある
  Max: 500

Metrics/CyclomaticComplexity:
  # app/models/area_plan.rb が16である
  Max: 16

Metrics/MethodLength:
  # app/controllers/concerns/preset.rb が65行ある
  Max: 65

Metrics/PerceivedComplexity:
  # app/models/area_plan.rb が17である
  Max: 17

Metrics/ModuleLength:
  # app/lib/gas_price_simulator.rb は159行ある
  Max: 160