include:
  # - 'Rakefile'
  - '**/*.rb'
exclude:
  - vendor/**/*
  - '.bundle/**/*'
  - 'spec/**/*'
  # - 'db/schema.rb'
  # - 'config/**/*'
  # - 'Guardfile'
  # - 'bin/**/*'
  # - 'lib/price-simulator/**/*'
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
reporters:
  - rubocop