version: 2
jobs:
  build:
    branches:
      only:
        - hoge
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install hub command 2.13.0
          command: |
            cd /tmp && wget https://github.com/github/hub/releases/download/v2.13.0/hub-linux-amd64-2.13.0.tgz
            tar xzf hub-linux-amd64-2.13.0.tgz
            cd hub-linux-amd64-2.13.0
            sudo ./install
      - run:
          name: Install bundler-diff, powered by sinsoku
          command: |
            gem install bundler-diff
      - run:
          name: Check whether 'bundler-diff' function is valid or not
          command: |
            git checkout -b foobar
            bundle update
            echo "bundle diff からの Pull request のテスト\n\n" > pull_request_message.txt
            bundle diff --format md_table >> pull_request_message.txt
            git add .
            git commit -m "bundle diff からの Pull request のテスト"
            git remote set-url origin https://corselia:$CIRCLECI_GIT_PASSWORD@github.com/corselia/challenging-rails.git
            git push --set-upstream origin foobar
            hub pull-request --file pull_request_message.txt --no-edit
      # - run:
      #     name: Install Bundler 2
      #     command: |
      #       gem install bundler
      # - run:
      #     name: Install Yarn
      #     command: |
      #       sudo apt-get install yarn -y
      # - run:
      #     name: install dependencies
      #     command: |
      #       bundle install --jobs=4 --retry=3 --path vendor/bundle
      # - save_cache:
      #     paths:
      #       - ./vendor/bundle
      #     key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # - run: bundle exec rake db:create
      # - run: bundle exec rake db:schema:load
      # run tests!
      # - run:
      #     name: run tests
      #     command: |
      #       mkdir /tmp/test-results
      #       TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
      #         circleci tests split --split-by=timings)"
      #       bundle exec rspec \
      #         --format progress \
      #         --format RspecJunitFormatter \
      #         --out /tmp/test-results/rspec.xml \
      #         --format progress \
      #         $TEST_FILES
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results
